### ISSUE TITLE
Running on a different language pair dataset 

### ISSUE THREAD

**Issue by harshading** [Ryou0634/placeholder_translation#1]
Hi,

What all changes do we need to make to run the experiments on a different language pair dataset?

Also, could you please clarify what filter_verb_dictionary.py script is doing? 

Thanks.

**Comment by ryokan0123** [comment]
> What all changes do we need to make to run the experiments on a different language pair dataset?

To do the experiments with different datasets, you need to do two things.
1. Modify [the config file](https://github.com/Ryou0634/placeholder_translation/blob/master/configs/lib/base.libsonnet) to specify the data.
2. You may also have to Implement a new [file parser](https://github.com/Ryou0634/placeholder_translation/blob/master/models/dataset_reader/file_parsers/parallel_file_parsers.py) accordingly and specify that on the config file.

I recommend referring to [the allennlp tutorial](https://guide.allennlp.org/) to familiarize yourself with the internal workings of the codebase. 

> could you please clarify what filter_verb_dictionary.py script is doing?

`filter_verb_dictionary.py` does a Japanese-language-specific preprocessing.
It leaves only a specific type of Japanese verb, "サ変動詞" (sa-hen verbs), which have relatively regular inflection rules.
Also, it compares the English and Japanese words and discards inconsistent data detected with string matching.

Hope this helps.
